create database ABM_CLIENTES;

use ABM_CLIENTES;

CREATE TABLE CLIENTES
(
CLIENTE_ID INT IDENTITY(1,1) PRIMARY KEY,
CLIENTE_NOMBRES VARCHAR(50),
CLIENTE_APELLIDOS VARCHAR(80),
CLIENTE_FECNAC DATETIME,
CLIENTE_CUIT VARCHAR(12),
CLIENTE_DOMICILIO VARCHAR(100),
CLIENTE_TELEFONO VARCHAR(10),
CLIENTE_EMAIL VARCHAR(40)
)

INSERT INTO CLIENTES(CLIENTE_NOMBRES, CLIENTE_APELLIDOS, CLIENTE_FECNAC, CLIENTE_CUIT, CLIENTE_DOMICILIO, CLIENTE_TELEFONO, CLIENTE_EMAIL)
VALUES ('PRUEBA1', 'APELLIDOPRUEBA1',1998-11-23,'11111111111','CALLE FALSA 123','1123456789','prueba@gmai.com')

select * from CLIENTES

begin tran
delete from CLIENTES where CLIENTE_ID = 1

rollback tran
